# -*- Makefile -*-

include ${XA_TOPSRCDIR}/mconfig
-include ${XA_TOPSRCDIR}/mconfig.*

obj-m                    += compat_xtables.o

obj-${build_CHAOS}       += xt_CHAOS.o
obj-${build_DELUDE}      += xt_DELUDE.o
obj-${build_ECHO}        += xt_ECHO.o
obj-${build_IPMARK}      += xt_IPMARK.o
obj-${build_LOGMARK}     += xt_LOGMARK.o
obj-${build_SYSRQ}       += xt_SYSRQ.o
obj-${build_TARPIT}      += xt_TARPIT.o
obj-${build_TEE}         += xt_TEE.o
obj-${build_condition}   += xt_condition.o
obj-${build_geoip}       += xt_geoip.o
obj-${build_ipp2p}       += xt_ipp2p.o
obj-${build_ipset}       += ipset/
obj-${build_portscan}    += xt_portscan.o
obj-${build_quota2}      += xt_quota2.o

-include ${M}/*.Kbuild
-include ${M}/Kbuild.*
