# -*- Makefile -*-

include ${XA_TOPSRCDIR}/mconfig
-include ${XA_TOPSRCDIR}/mconfig.*

obj-m                += compat_xtables.o

obj-${build_CHAOS}   += xt_CHAOS.o
obj-${build_DELUDE}  += xt_DELUDE.o
obj-${build_LOGMARK} += xt_LOGMARK.o
obj-${build_TARPIT}  += xt_TARPIT.o
obj-${build_TEE}     += xt_TEE.o
obj-${build_portscan} += xt_portscan.o

-include ${M}/*.Kbuild
